name: Convert AI Files Using Illustrator

on:
  push:
    paths:
      - '**.ai'
      - '**.jsx'
      - '.github/workflows/**'

jobs:
  illustrator-job:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Illustrator JSX Script from Trusted Folder
        run: |
          echo Running Illustrator JSX script from trusted folder...
          "C:\Program Files\Adobe\Adobe Illustrator 2025\Support Files\Contents\Windows\Illustrator.exe" "run.jsx"
        working-directory: "C:\\Program Files\\Adobe\\Adobe Illustrator 2025\\Presets\\en_US\\Scripts"
        shell: cmd
